name: Radar Busca-Casa Cloud
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-radar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install selenium webdriver-manager requests

      - name: Run Script
        env:
          PASSWORD_APP: ${{ secrets.PASSWORD_APP }}
          MY_COOKIES: ${{ secrets.MY_COOKIES }}
        run: |
          HOUR=$(date +%H)
          if [ "$HOUR" == "12" ]; then
            python radar.py --daily
          else
            python radar.py
          fi

      - name: Save State
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add estado_mercado.json
          git commit -m "Update state" || echo "No changes"
          git push
